### ISSUE TITLE
aprilslam-the use of the problem

### ISSUE THREAD

**Issue by hajungong007** [ProjectArtemis/aprilslam#2]
we are working on a ardrone 2.0 to landing on the apriltags,so "subscribeCamera("image_raw")" had been modified to "subscribeCamera("/ardrone/front/image_raw")".
We have Ubuntu 14.04 and ROS Indigo running on my Notebook computer.
However,we have some of the problem with the aprilslam, seeing picture.
![Uploading Screenshot from 2016-02-23 15:24:20.png…]()

**Comment by hajungong007** [comment]
![Uploading Screenshot from 2016-02-23 15:24:20.png…]()
![Uploading Screenshot from 2016-02-23 15:29:37.png…]()
![Uploading rosgraph.png…]()

**Comment by mhkabir** [comment]
Fixed? :)

**Comment by hajungong007** [comment]
yes

**Comment by walkeryu123** [comment]
I meet the same problem,can you tell me how to solve it?
