### ISSUE TITLE
how does the /tf  be published

### ISSUE THREAD

**Issue by walkeryu123** [ProjectArtemis/aprilslam#5]
I run the bag successfully, when I use "rqt_graph" ,It shows as follows,
![qq 20160509205154](https://cloud.githubusercontent.com/assets/13862040/15113637/0d5e5fe6-1628-11e6-9d62-a93853e9b21d.jpg)
"rostopic echo /tf " seems to work fine,but when i run "rostopic echo /usb_cam/mapper ", /usb_cam/mapper seems unpublished, which data is used by /tf?

**Comment by mhkabir** [comment]
That's a node. It publishes the TF..

**Comment by walkeryu123** [comment]
Thank you,can you tell me  /TF get the data from  which node?

**Comment by mhkabir** [comment]
Mapper nkde
