### ISSUE TITLE
AprilSlam without RViz

### ISSUE THREAD

**Issue by akshayshetty** [ProjectArtemis/aprilslam#6]
Hi,

Can I use this package without RViz? I plan to implement it on an Odroid without installing visual tools like RViz.

Also, I plan to use the following tags: http://www.dotproduct3d.com/assets/pdf/apriltags.pdf
Just to confirm, I would have to set to black border to 1, right?

Thank  you!

**Comment by akshayshetty** [comment]
Hi,

So I ended up installing RViz because AprilSlam needed some rviz header files. But I removed the rviz node from the slam.launch file.

I am able to detect tags and see the pose in /tf topic. What is the expected rate of output? I have images coming in at about 30fps, and I am getting /tf output from AprilSlam at about 1.5Hz.

**Comment by mhkabir** [comment]
Hmm. Yeah it would be simple to get rid of the RViz dependencies. It's strictly not RViz, but rather the rviz messages and data types. Will see if it can be better done.

**Comment by mhkabir** [comment]
The slow output probably points at the Odroid not being able to process frames fast enough, but I would've expected better performance. 
Can you try to hunt down the performance bottleneck? I can try to do this sometime next week, but no guarantees. I haven't run this on ARM in a long time, but it used to run just fine.

**Comment by akshayshetty** [comment]
Hi, sorry for the delay. Will look into this soon and post here.

**Comment by akshayshetty** [comment]
Taking a quick look at the topics from the rqt_graph:

![aprilslam_rosgraph](https://cloud.githubusercontent.com/assets/11767355/17376932/e75f8c44-59f6-11e6-98aa-16b89830f544.png)

The bottleneck is somewhere in the detector node.

I am publishing images to /mv_25001964/image_raw at 30 frames per second. The topics coming out of the detector node are at roughly 1.8 Hz. The mapper node doesn't seem to be slowing down the rate too much and the /tf topics are also published at 1.8 Hz.
