### ISSUE TITLE
detecting tags from bag file

### ISSUE THREAD

**Issue by mohit-agr** [ProjectArtemis/aprilslam#7]
Hi

I am playing a bag file that has recorded image stream. The topics include /cam0/image_raw and cam1/image_raw. There is no cam_info topic.
I have been trying to run the AprilTag detection (mapping is not necessary at the moment) and have modified the slam.launch file with :
            arg name="camera" value="/cam0"

In the rViz, I can see the image stream but the detections are not shown. Is there some problem with my settings? Could you please tell me what I need to add?

Apologies if the question seems trivial. I am new to ROS.

**Comment by mhkabir** [comment]
What kind of tags are they? Are you on current master? Read the readme about the black border.

**Comment by mohit-agr** [comment]
they are april tags 36h11 (I am using two at the moment, id 8 and 11). I did read about the black border and made the change in TagFamily.cc

**Comment by mhkabir** [comment]
Are you feeding rectified images?

**Comment by mohit-agr** [comment]
No. Is it really necessary just for detection?
