### ISSUE TITLE
Broken Link : Error 404 to the download link of April Tags

### ISSUE THREAD

**Issue by munkarkin96** [ProjectArtemis/aprilslam#8]
"""
The default AprilTag family used is 36h11 with a black border of 1. A PDF of the tag family is available here : http://www.dotproduct3d.com/assets/pdf/apriltags.pdf
"""

As quoted from your instruction, the link appears to be broken. Please advice. Thanks.

**Comment by mhkabir** [comment]
https://www.dotproduct3d.com/uploads/8/5/1/1/85115558/apriltags1-20.pdf

**Comment by munkarkin96** [comment]
Thanks.
